import React from "react";

const Review = () => {
  return (
    <div className="preference">
      <div className="container">
        <div className="row gx-4 gy-3">
          <div className="col-12 col-lg-6">
            <h2 className="text-dark">Step 2: Review and React</h2>
          </div>
          <div className="col-12 col-lg-6">
            <p className="text-dark">
              Peruse the logos generated by our API and use the Like, Neutral,
              and Dislike buttons to provide feedback for each design. Our
              system will learn from your preferences, making sure the final
              result is as close to perfection as possible!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Review;
